#!/usr/bin/env bash
# script: generate-indexes.sh
# description: Pre-build master index and skills catalog for each team group.
#              Run this in the library whenever skills or teams are added/removed.
#              The output (_generated/) is committed so target repos pick up changes via symlinks.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIBRARY_DIR="$(dirname "$SCRIPT_DIR")"
GENERATED_DIR="$LIBRARY_DIR/_generated"

SKIP_DIRS="company scripts _generated .git .github"

find_teams() {
    for dir in "$LIBRARY_DIR"/*/; do
        local name
        name=$(basename "$dir")
        if echo "$SKIP_DIRS" | grep -qw "$name"; then
            continue
        fi
        if [[ -f "$dir/AGENTS.md" ]]; then
            echo "$name"
        fi
    done
}

generate_skills_index() {
    local team="$1"
    local output="$2"

    cat << 'HEADER' > "$output"
# Available Skills

Auto-generated by `generate-indexes.sh`. Do not edit manually.

HEADER

    if [[ -d "$LIBRARY_DIR/company/skills" ]]; then
        echo "## Company Skills" >> "$output"
        echo "" >> "$output"
        find "$LIBRARY_DIR/company/skills" -maxdepth 2 -name "SKILL.md" | sort | while read -r skill_file; do
            local skill_name
            skill_name=$(basename "$(dirname "$skill_file")")
            echo "- [$skill_name](company-links/$skill_name/SKILL.md)" >> "$output"
            echo "@.agents/skills/company-links/$skill_name/SKILL.md" >> "$output"
        done
        echo "" >> "$output"
    fi

    if [[ -d "$LIBRARY_DIR/$team/skills" ]]; then
        echo "## Team ($team) Skills" >> "$output"
        echo "" >> "$output"
        find "$LIBRARY_DIR/$team/skills" -maxdepth 2 -name "SKILL.md" | sort | while read -r skill_file; do
            local skill_name
            skill_name=$(basename "$(dirname "$skill_file")")
            echo "- [$skill_name]($team-links/$skill_name/SKILL.md)" >> "$output"
            echo "@.agents/skills/$team-links/$skill_name/SKILL.md" >> "$output"
        done
        echo "" >> "$output"
    fi
}

generate_master_index() {
    local team="$1"
    local output="$2"

    cat << EOF > "$output"
## AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ## 
# AI Agent Master Configuration Index

Auto-generated by \`generate-indexes.sh\`. Do not edit manually.

## Shared Rules
@.agents/rules/agents-company-link
@.agents/rules/agents-$team-link

- [Company Rules](rules/agents-company-link)
- [Team Rules ($team)](rules/agents-$team-link)

## Available Skills
@.agents/skills/AGENTS.md
- [Skills Catalog](skills/AGENTS.md)
EOF
}

echo "Generating indexes..."

rm -rf "$GENERATED_DIR"

TEAMS=$(find_teams)
if [[ -z "$TEAMS" ]]; then
    echo "Warning: No team directories found. Nothing to generate."
    exit 0
fi

for team in $TEAMS; do
    echo "  $team"
    mkdir -p "$GENERATED_DIR/$team"
    generate_master_index "$team" "$GENERATED_DIR/$team/master-index.md"
    generate_skills_index "$team" "$GENERATED_DIR/$team/skills-index.md"
done

echo ""
echo "Done. Generated indexes for: $TEAMS"
echo "Output: _generated/"
echo ""
echo "Commit these files so target repos pick up changes via their existing symlinks."
