#!/usr/bin/env bash
# script: generate-indexes.sh
# description: Pre-build master index and skills catalog for each group.
#              Run this in the library whenever skills or groups are added/removed.
#              The output (_generated/) is committed so target repos pick up changes via symlinks.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIBRARY_DIR="$(dirname "$SCRIPT_DIR")"
GENERATED_DIR="$LIBRARY_DIR/_generated"

GROUPS_DIR="$LIBRARY_DIR/groups"

generate_skills_index() {
    local group="$1"
    local output="$2"

    cat << 'HEADER' > "$output"
# Available Skills

Auto-generated by `generate-indexes.sh`. Do not edit manually.

HEADER

    if [[ -d "$LIBRARY_DIR/global/skills" ]]; then
        echo "## Global Skills" >> "$output"
        echo "" >> "$output"
        find "$LIBRARY_DIR/global/skills" -maxdepth 2 -name "SKILL.md" | sort | while read -r skill_file; do
            local skill_name
            skill_name=$(basename "$(dirname "$skill_file")")
            echo "- [$skill_name](global-links/$skill_name/SKILL.md)" >> "$output"
            echo "@.agents/skills/global-links/$skill_name/SKILL.md" >> "$output"
        done
        echo "" >> "$output"
    fi

    if [[ -d "$GROUPS_DIR/$group/skills" ]]; then
        echo "## Group ($group) Skills" >> "$output"
        echo "" >> "$output"
        find "$GROUPS_DIR/$group/skills" -maxdepth 2 -name "SKILL.md" | sort | while read -r skill_file; do
            local skill_name
            skill_name=$(basename "$(dirname "$skill_file")")
            echo "- [$skill_name]($group-links/$skill_name/SKILL.md)" >> "$output"
            echo "@.agents/skills/$group-links/$skill_name/SKILL.md" >> "$output"
        done
        echo "" >> "$output"
    fi
}

generate_master_index() {
    local group="$1"
    local output="$2"

    cat << EOF > "$output"
## AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ## 
# AI Agent Master Configuration Index

Auto-generated by \`generate-indexes.sh\`. Do not edit manually.

## Shared Rules
@.agents/rules/agents-global-link
@.agents/rules/agents-$group-link

- [Global Rules](rules/agents-global-link)
- [Group Rules ($group)](rules/agents-$group-link)

## Available Skills
@.agents/skills/AGENTS.md
- [Skills Catalog](skills/AGENTS.md)
EOF
}

echo "Generating indexes..."

rm -rf "$GENERATED_DIR"

FOUND_GROUPS=()
if [[ -d "$GROUPS_DIR" ]]; then
    for dir in "$GROUPS_DIR"/*/; do
        [[ -d "$dir" ]] || continue
        name=$(basename "$dir")
        if [[ -f "$dir/AGENTS.md" ]]; then
            FOUND_GROUPS+=("$name")
        fi
    done
fi

if [[ ${#FOUND_GROUPS[@]} -eq 0 ]]; then
    echo "Warning: No group directories found. Nothing to generate."
    exit 0
fi

for group in "${FOUND_GROUPS[@]}"; do
    echo "  $group"
    mkdir -p "$GENERATED_DIR/$group"
    generate_master_index "$group" "$GENERATED_DIR/$group/master-index.md"
    generate_skills_index "$group" "$GENERATED_DIR/$group/skills-index.md"
done

echo ""
echo "Done. Generated indexes for: ${FOUND_GROUPS[*]}"
echo "Output: _generated/"
echo ""
echo "Commit these files so target repos pick up changes via their existing symlinks."
