#!/usr/bin/env bash
# script: setup.sh
# description: Set up AI agent configuration in a target repository.
#              Creates local symlinks only — never commits or pushes.
#              Supports multiple groups per repo (e.g., --group backend --group infra).
#              Run once per repo. Updates propagate automatically via symlinks
#              when the library is pulled.

set -euo pipefail

# Colors (disabled if stdout is not a terminal)
if [[ -t 1 ]]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[0;33m'
    CYAN='\033[0;36m'
    BOLD='\033[1m'
    DIM='\033[2m'
    RESET='\033[0m'
    CHECK="${GREEN}✔${RESET}"
    CROSS="${RED}✘${RESET}"
    ARROW="${CYAN}→${RESET}"
else
    RED='' GREEN='' YELLOW='' CYAN='' BOLD='' DIM='' RESET=''
    CHECK='✔' CROSS='✘' ARROW='→'
fi

info()  { echo -e "  ${DIM}$1${RESET}"; }
step()  { echo -e "  ${CHECK}  $1"; }
err()   { echo -e "  ${CROSS}  ${RED}$1${RESET}" >&2; }

usage() {
    cat << EOF
${BOLD}Usage:${RESET} $0 [OPTIONS]

Set up AI agent configuration in a target repository. Supports Cursor, Claude Code, Codex, and Antigravity.

${BOLD}Options:${RESET}
  -t, --target <path>   Target repository path (required)
  -g, --group <name>    Group name in the config library (repeatable, at least one required)
  -h, --help            Show this help message

${BOLD}Examples:${RESET}
  # Single group
  $0 --target ../my-repo --group infrastructure

  # Multiple groups (monorepo with backend + infra)
  $0 --target ../my-monorepo --group backend --group infrastructure

  # Multiple groups (frontend project using shared language rules)
  $0 --target ../web-app --group frontend --group typescript
EOF
    exit 1
}

TARGET=""
SELECTED_GROUPS=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        -t|--target)
            TARGET="$2"
            shift 2
            ;;
        -g|--group)
            SELECTED_GROUPS+=("$2")
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            err "Unknown option: $1"
            echo ""
            usage
            ;;
    esac
done

if [[ -z "$TARGET" || ${#SELECTED_GROUPS[@]} -eq 0 ]]; then
    err "--target and at least one --group are required."
    echo ""
    usage
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIBRARY_DIR="$(dirname "$SCRIPT_DIR")"

if [[ ! -d "$TARGET" ]]; then
    err "Target directory '$TARGET' does not exist."
    exit 1
fi

TARGET_DIR="$(cd "$TARGET" && pwd)"

GROUPS_DIR="$LIBRARY_DIR/groups"

for GROUP in "${SELECTED_GROUPS[@]}"; do
    if [[ ! -d "$GROUPS_DIR/$GROUP" ]]; then
        err "Group '$GROUP' does not exist in the library ($GROUPS_DIR/$GROUP)."
        exit 1
    fi
done

AGENTS_DIR="$TARGET_DIR/.agents"

echo ""
echo -e "${BOLD}Setting up AI agent configuration${RESET}"
echo -e "  Target:  ${CYAN}$TARGET_DIR${RESET}"
echo -e "  Groups:  ${CYAN}${SELECTED_GROUPS[*]}${RESET}"
echo ""

# 1. Create directory structure
mkdir -p "$AGENTS_DIR/rules"
mkdir -p "$AGENTS_DIR/skills"

for GROUP in "${SELECTED_GROUPS[@]}"; do
    rm -rf "$AGENTS_DIR/$GROUP"
done
step "Created directory structure"

# 2. Symlink global rules
REL_GLOBAL_AGENTS=$(realpath --relative-to="$AGENTS_DIR/rules" "$LIBRARY_DIR/global/AGENTS.md")
ln -sfn "$REL_GLOBAL_AGENTS" "$AGENTS_DIR/rules/agents-global-link"
step "Linked global rules"

# 3. Symlink group rules
for GROUP in "${SELECTED_GROUPS[@]}"; do
    REL_GROUP_AGENTS=$(realpath --relative-to="$AGENTS_DIR/rules" "$GROUPS_DIR/$GROUP/AGENTS.md")
    ln -sfn "$REL_GROUP_AGENTS" "$AGENTS_DIR/rules/agents-$GROUP-link"
done
step "Linked group rules  ${DIM}(${SELECTED_GROUPS[*]})${RESET}"

# 4. Symlink global skills
if [[ -d "$LIBRARY_DIR/global/skills" ]]; then
    REL_GLOBAL_SKILLS=$(realpath --relative-to="$AGENTS_DIR/skills" "$LIBRARY_DIR/global/skills")
    ln -sfn "$REL_GLOBAL_SKILLS" "$AGENTS_DIR/skills/global-links"
fi

# 5. Symlink group skills
SKILL_GROUPS=()
for GROUP in "${SELECTED_GROUPS[@]}"; do
    if [[ -d "$GROUPS_DIR/$GROUP/skills" ]]; then
        REL_GROUP_SKILLS=$(realpath --relative-to="$AGENTS_DIR/skills" "$GROUPS_DIR/$GROUP/skills")
        ln -sfn "$REL_GROUP_SKILLS" "$AGENTS_DIR/skills/$GROUP-links"
        SKILL_GROUPS+=("$GROUP")
    fi
done
step "Linked skills        ${DIM}(global${SKILL_GROUPS[*]:+, ${SKILL_GROUPS[*]}})${RESET}"

# 6. Generate composite master index (supports multiple groups)
MASTER_INDEX="$AGENTS_DIR/AGENTS.md"
rm -f "$MASTER_INDEX"
cat << 'HEADER' > "$MASTER_INDEX"
## AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ##
# AI Agent Master Configuration Index

Auto-generated by `setup.sh`. Do not edit manually.

## Shared Rules
HEADER

echo "@.agents/rules/agents-global-link" >> "$MASTER_INDEX"
echo "" >> "$MASTER_INDEX"
for GROUP in "${SELECTED_GROUPS[@]}"; do
    echo "@.agents/rules/agents-$GROUP-link" >> "$MASTER_INDEX"
done
echo "" >> "$MASTER_INDEX"
echo "- [Global Rules](rules/agents-global-link)" >> "$MASTER_INDEX"
for GROUP in "${SELECTED_GROUPS[@]}"; do
    echo "- [Group Rules ($GROUP)](rules/agents-$GROUP-link)" >> "$MASTER_INDEX"
done
echo "" >> "$MASTER_INDEX"
echo "## Available Skills" >> "$MASTER_INDEX"
echo "@.agents/skills/AGENTS.md" >> "$MASTER_INDEX"
echo "- [Skills Catalog](skills/AGENTS.md)" >> "$MASTER_INDEX"

# 7. Generate composite skills index
SKILLS_INDEX="$AGENTS_DIR/skills/AGENTS.md"
rm -f "$SKILLS_INDEX"
cat << 'HEADER' > "$SKILLS_INDEX"
# Available Skills

Auto-generated by `setup.sh`. Do not edit manually.

HEADER

if [[ -d "$LIBRARY_DIR/global/skills" ]]; then
    echo "## Global Skills" >> "$SKILLS_INDEX"
    echo "" >> "$SKILLS_INDEX"
    find "$LIBRARY_DIR/global/skills" -maxdepth 2 -name "SKILL.md" | sort | while read -r skill_file; do
        skill_name=$(basename "$(dirname "$skill_file")")
        echo "- [$skill_name](global-links/$skill_name/SKILL.md)" >> "$SKILLS_INDEX"
        echo "@.agents/skills/global-links/$skill_name/SKILL.md" >> "$SKILLS_INDEX"
    done
    echo "" >> "$SKILLS_INDEX"
fi

for GROUP in "${SELECTED_GROUPS[@]}"; do
    if [[ -d "$GROUPS_DIR/$GROUP/skills" ]]; then
        echo "## Group ($GROUP) Skills" >> "$SKILLS_INDEX"
        echo "" >> "$SKILLS_INDEX"
        find "$GROUPS_DIR/$GROUP/skills" -maxdepth 2 -name "SKILL.md" | sort | while read -r skill_file; do
            skill_name=$(basename "$(dirname "$skill_file")")
            echo "- [$skill_name]($GROUP-links/$skill_name/SKILL.md)" >> "$SKILLS_INDEX"
            echo "@.agents/skills/$GROUP-links/$skill_name/SKILL.md" >> "$SKILLS_INDEX"
        done
        echo "" >> "$SKILLS_INDEX"
    fi
done
step "Generated composite indexes"

# 8. Manage root AGENTS.md
ROOT_AGENTS="$TARGET_DIR/AGENTS.md"
MANAGED_START="<!-- AGENTS_MANAGED_START -->"
MANAGED_END="<!-- AGENTS_MANAGED_END -->"

MANAGED_CONTENT=$(cat << EOF
$MANAGED_START
## AI Agent Configuration (Managed)
> [!NOTE]
> This section is automatically managed by the config library setup script.

### Shared Agent Rules & Skills
@.agents/AGENTS.md
- [Master Configuration Index](.agents/AGENTS.md)
$MANAGED_END
EOF
)

if [[ ! -f "$ROOT_AGENTS" ]]; then
    echo "# Project Agent Rules" > "$ROOT_AGENTS"
    echo "" >> "$ROOT_AGENTS"
    echo "$MANAGED_CONTENT" >> "$ROOT_AGENTS"
    echo "" >> "$ROOT_AGENTS"
    echo "## Project-specific Rules" >> "$ROOT_AGENTS"
    echo "Add your repository-level rules here." >> "$ROOT_AGENTS"
    step "Created root AGENTS.md"
else
    if grep -q "$MANAGED_START" "$ROOT_AGENTS"; then
        sed -i "/$MANAGED_START/,/$MANAGED_END/d" "$ROOT_AGENTS"
        echo "$MANAGED_CONTENT" >> "$ROOT_AGENTS"
    else
        echo "" >> "$ROOT_AGENTS"
        echo "$MANAGED_CONTENT" >> "$ROOT_AGENTS"
    fi
    step "Updated root AGENTS.md"
fi

# 9. Update .gitignore
GITIGNORE="$TARGET_DIR/.gitignore"

add_to_gitignore() {
    local pattern="$1"
    if [[ ! -f "$GITIGNORE" ]]; then
        echo "$pattern" > "$GITIGNORE"
    elif ! grep -qxF "$pattern" "$GITIGNORE"; then
        echo "$pattern" >> "$GITIGNORE"
    fi
}

add_to_gitignore "# AI Agent Configuration (managed by agentic-ai-library)"
add_to_gitignore ".agents/"
add_to_gitignore "AGENTS.local.md"
step "Updated .gitignore"

# Done
echo ""
echo -e "${GREEN}${BOLD}  Setup complete!${RESET}"
echo ""
echo -e "  ${ARROW} Rules and skills are symlinked to the library."
echo -e "  ${ARROW} Run ${CYAN}git pull${RESET} in the library to propagate updates."
echo -e "  ${ARROW} Re-run this script only to add or remove groups."
echo ""
